name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      -
        name: Build TUSD
        run: ./scripts/build_all.sh

      -
        name: GitHub Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: tusd_*.*
